local_dir: G:\OpenData
drive_dir: /content/drive/MyDrive/NeuroScience/OpenData/
allen_name: allen_npixels2
ibl_name: IBLdata
allen_manifest: visual-behavior-neuropixels_project_manifest_v0.4.0.json
output_name: OpenDataResults
gpfa_params:
  gpfa_window: 1.0
  gpfa_binsize: 50
cca_params:
  cca_window: 1.0
  cca_binsize: 50
allen_brain_regions: [["CA1", "TH", "SUB"], ["VISp", "LGv", "TH"]]
ibl_brain_regions:
  [
    ["CA1", "TH", "SUB"],
    [["VISp1", "VISp2/3", "VISp4", "VISp5", "VISp6a", "VISp6b"], "LGv", "TH"],
  ]
allen_cca_regions:
  [
    ["CA1", "SUB"],
    ["CA1", "TH"],
    ["SUB", "TH"],
    ["VISp", "LGv"],
    ["VISp", "TH"],
    ["LGv", "TH"],
  ]
ibl_cca_regions:
  [
    ["CA1", "SUB"],
    ["CA1", "TH"],
    ["SUB", "TH"],
    [["VISp1", "VISp2/3", "VISp4", "VISp5", "VISp6a", "VISp6b"], "LGv"],
    [["VISp1", "VISp2/3", "VISp4", "VISp5", "VISp6a", "VISp6b"], "TH"],
    ["LGv", "TH"],
  ]
ibl_filter_properties:
  presence_ratio: [">", 0.9]
  contamination: ["<", 0.4]
  noise_cutoff: ["<", 25]
  amp_median: [">", 0.00004]
  firing_rate: [">", 0.5]
allen_filter_properties:
  isi_violations: ["<", 0.4]
  amplitude_cutoff: ["<", 0.1]
  presence_ratio: [">", 0.9]
  firing_rate: [">", 0.5]
